apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - image-id-registry.yaml
  - logic-compiler-api.yaml
  - proof-generation-service.yaml
  - zk-verification-service.yaml
  - zcash-backend.yaml
  - build-service.yaml

commonLabels:
  app.kubernetes.io/part-of: khafi-gateway
  app.kubernetes.io/managed-by: kustomize
