apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: khafi

resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - ../backend
  - ../frontend
  # Ingress/IngressRoute included via traefik overlay
  - ../ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: khafi-gateway
  app.kubernetes.io/managed-by: kustomize
